apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mini-kube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-mini-kube
  template:
    metadata:
      labels:
        app: my-mini-kube
    spec:
      containers:
      - name: my-mini-kube
        image: sunder3422/my-mini-kube-jar
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080